добавление конвертора для игроков
justVitalius/quiz-telegram-bot pull request #40
Opened 2018-04-24 18:39 UTC by GlebSa

2018-04-24 18:42 UTC, justvitalius approved these changes

2018-04-25 16:48 UTC, w3dip commented on src/statistics/endpoints.js
>  };
еще нужны категории

2018-04-25 16:50 UTC, w3dip commented on src/statistics/convertor.js
> +const { getAllUsers } = require("../database");
я так понимаю в связи с изменениями в https://github.com/justVitalius/quiz-telegram-bot/pull/42 надо лазить в БД, брать все вопросы и потом это дополнять при маппинге, т.е. Виталя убрал сами вопросы из профиля пользователя

2018-04-25 16:51 UTC, w3dip commented on src/statistics/convertor.js
> +        answers: user.answers.map(answer => {
map(answer надо бы переименовать, т.к. user.answers это по сути вопросы на самом деле, т.е. (answer => { можно переименовать в question, тогда не будет конструкций вида answer.answer.isCorrect

2018-04-25 17:24 UTC, w3dip requested changes
комментарии

2018-04-26 06:38 UTC, justVitalius commented on src/statistics/convertor.js
> +const { getAllUsers } = require("../database");
Согласно нашему описанию API #16 - полная инфа о вопросах не нужна.
На данном этапе это обеспечит некую сохранность данных, чтобы никто не слил себе на комп все вопросы с ответами

2018-04-26 06:38 UTC, justVitalius commented on src/statistics/convertor.js
> +        answers: user.answers.map(answer => {
Да, согласно #42 исчезает конструкция answers.$.answer.

2018-05-01 09:12 UTC, justvitalius requested changes

2018-05-01 09:12 UTC, justVitalius commented on src/statistics/convertor.js
> +            isCorrect: answer.answer.isCorrect,
Согласно #42 исчезает конструкция answers.$.answer.
Необходимо использовать актуальный код, а не устаревшую версию с продакшн.сервера

2018-05-02 13:45 UTC, w3dip commented
Сделано все в рамках https://github.com/justVitalius/quiz-telegram-bot/pull/44, этот ПР не принимать

2018-05-03 20:05 UTC, justvitalius commented
@GlebSa сделал риквест #50. Теперь можно опираться на схему данных в БД. Добавил описание объекта, который в answers сохраняется.

2018-05-05 13:47 UTC, justVitalius commented
@GlebSa добавил тест на конвертор категорий.
Не смог добавить тест на конвертор игроков. Для них нужен пулриквест #51

2018-05-07 16:53 UTC, justVitalius commented
По всеобщему мнению - пулриквест потерял актуальность.
Закрываю.

2018-05-07 16:53 UTC, closed without merging