Исправление дефектов в работе бота
justVitalius/quiz-telegram-bot pull request #46
Opened 2018-05-03 09:52 UTC by w3dip

1) Исправлен дефект мигратора (добавление undefined категорий)
2) Исправлен процесс проверки ответа (в клавиатуру было лобавление номера кнопки начиная с 0, нумерация же правильных ответов в data.js идет с единицы)
3) Одни и те же вопросы не задаются повторно (в паре мест пришлось отказаться от ramda)
4) Сделано API для статистики
5) По окончании ответов рнавопросы пользователю выдается сообщение и выставляется статус end

2018-05-03 09:54 UTC, w3dip commented on src/bot/game/actions.js
> +          .filter(gamer => gamer.status !== FINISH_STATUS)
не отправляем вопросы пользователям, уже на все ответившим

2018-05-03 09:55 UTC, w3dip commented on src/bot/game/actions.js
> +  questionnaires = R.filter(questionnaire => {
не задаем одни и те же вопросы повторно

2018-05-03 09:55 UTC, w3dip commented on src/bot/game/pipes.js
> +      return Object.assign({}, payload, {
вариант через R.mergeDeepRight не работает

2018-05-03 09:56 UTC, w3dip commented on src/bot/index.js
> +        if (replies) {
добавляем проверку, чтобы если нужно просто отдать сообщение (в конце ответов на вопросы), то чтобы не рисовать клавиатуру

2018-05-03 09:57 UTC, w3dip commented on src/bot/user/answers.js
> +    questionnaireId: _id.toString(),
вариант R.compose(R.toString, R.propOr({}, "_id"))(questionnaire), не работает, видимо все део в том, что это объект модели mongo и с _id там все время проблемы

2018-05-03 09:58 UTC, w3dip commented on src/migrator/index.js
> +                    if (category) {
в data.js может не быть категории (как сейчас закомичено, на один из вопросов нет категории), чтобы не было дефекта проверяем здесь, что категория есть

2018-05-03 20:16 UTC, justvitalius requested changes
Пожалуйста, измени фильтрацию FINISH_STATUS пользователей и вывод сообщения "спасибо, до свидания!" для них

2018-05-03 20:16 UTC, justVitalius commented on src/bot/game/actions.js
> +          .filter(gamer => gamer.status !== FINISH_STATUS)
Зацени код здесь https://github.com/justVitalius/quiz-telegram-bot/blob/master/src/bot/user/index.js#L57

Он отбирает только определенных пользователей.
Это вообще странно, что сюда попадают пользователи в статусе `FINISH_STATUS`.

Давай все же отдельно обработаем пользователей с этим статусом в отдельной функции внутри setInterval. Чтобы не смешивать их с потоком "ожидающих сообщений".

2018-05-03 20:16 UTC, justVitalius commented on src/bot/game/pipes.js
> +      return Object.assign({}, payload, {
Да. Странно, что этот код остался тут О_о

2018-05-03 20:16 UTC, justVitalius commented on src/bot/user/answers.js
> +    questionnaireId: _id.toString(),
Да, он не личный атрибут объекта, `hasOwnProperty('_id')` возвращает `false`.

2018-05-03 20:16 UTC, justVitalius commented on src/bot/index.js
> +        if (replies) {
Правильней будет формировать только такой [] messages, который содержит вопросы и варианты ответа. А если пользователю больше нельзя выдавать вопросы, то нужно просто исключать его отсюда и выставлять ему статус `FINISH_STATUS` и отсылать сообщение "спасибо, до свидания!" в отдельном потоке.

2018-05-07 16:53 UTC, justVitalius commented
Все дефекты были поправлены в других пулриквестах.
Этот закрываю.

2018-05-07 16:53 UTC, closed without merging