feature/webhook_start Работа бота через вэбхуки
justVitalius/quiz-telegram-bot pull request #49
Opened 2018-05-03 15:32 UTC by w3dip

2018-05-03 15:36 UTC, w3dip commented
принимать после https://github.com/justVitalius/quiz-telegram-bot/pull/46

2018-05-03 20:19 UTC, justVitalius commented
Тесты не проходят :( Вынужден отклонить. Плюс к этому, этот риквест содержит #46. ВНачале нужно его принять. И потом этот отрибейзить

2018-05-03 20:19 UTC, justvitalius requested changes

2018-05-03 20:19 UTC, justVitalius commented on src/bot/index.js
> +const options = {
Так может это тоже в `config/default.js` перенести полные пути. Там тоже можно писать __dirname.

2018-05-07 16:54 UTC, justVitalius commented
Ждем рибейза относительно master.
Чтобы была только доработка по вебхукам.

Что касается сертификата, то решили на вечерней встрече, что гегенрить сертификаты будут под каждую машину через ansible. И лежать они будут в диреткории ~/www

2018-05-12 11:59 UTC, closed without merging

2018-05-12 12:00 UTC, justVitalius commented
Переоткрыт в #59