Добавлена справка и заменено удаление на очистку профиля игрока.
justVitalius/quiz-telegram-bot pull request #62
Opened 2018-05-13 12:31 UTC by justVitalius

Добавлена справка по /help. Текст еще на тестировании поправим.
И нужно вбить туда "цель бота" для конференции. #53 можно закрывать.

На команду /clear убрано удаление пользователей. Подумал, так правильнее. И это позволит существующим игрокам на проме отсылать приглашения пройти тестирование заново.

2018-05-13 18:58 UTC, w3dip approved these changes

2018-05-13 20:28 UTC, w3dip requested changes

2018-05-13 20:28 UTC, w3dip commented on src/bot/game/actions.js
> +          reject({
Это сообщение не будет выведено

2018-05-13 20:28 UTC, w3dip commented on src/bot/messages/index.js
> +Перед вами telegram опросник от Сбербан Технологии.
Сбербанк, к нет

2018-05-13 20:28 UTC, w3dip commented on src/bot/messages/index.js
> +Общий доступ приурочен по случаю HolyJS 2018.
Текст можно задать указав в @BotFather через
/setabouttext

Тест по javascript от компании АО "Сбертех" для конференции HolyJS2018

2018-05-13 20:28 UTC, w3dip commented on src/bot/messages/index.js
> +Бот будет присылать вопросы по фронтенду и javascript технологиям.
Текст можно задать через

/setdescription


Предлагается текст:

Добро пожаловать!
Бот будет присылать вопросы по frontend и javascript технологиям.
Ваша задача - выбрать один правильный вариант ответа.
Ответ засчитывается только после нажатия на кнопку под вопросом.
Любое написанное боту сообщение игнорируется (кроме досутпных команд).

Дедлайна нет. Ограничений по времени нет (в течение конференции - 2 дня).

Чтобы увидеть список доступных команд введите / и далее система подскажет возможные варианты

2018-05-13 20:28 UTC, w3dip commented on src/bot/messages/index.js
> +<b>Команды бота:</b>
Для задания команд можно использовать
/setcommands

Отправив текст

start - Начать тестирование
clear - Очистить историю ответов и начать заново

2018-05-13 20:29 UTC, w3dip commented on src/bot/messages/index.js
> +<b>Команды бота:</b>
Указанные изменения ууже применены к @HolyJS2018Bot

2018-05-14 19:15 UTC, justVitalius commented on src/bot/game/actions.js
> +          reject({
+1.
Немного переделал.

2018-05-14 19:15 UTC, justVitalius commented on src/bot/messages/index.js
> +Перед вами telegram опросник от Сбербан Технологии.
Поправил.

2018-05-14 19:16 UTC, justVitalius commented on src/bot/messages/index.js
> +Бот будет присылать вопросы по фронтенду и javascript технологиям.
Принято. Но ограничение в 512 символов. 👎 
Текст еще поправим после обсуждения его с hr.

2018-05-14 19:16 UTC, justVitalius commented on src/bot/messages/index.js
> +<b>Команды бота:</b>
Принято.

2018-05-14 20:00 UTC, justVitalius commented
@w3dip перевел улучшение справки в #48.

2018-05-14 20:03 UTC, merged